except_occupation = [
    'Summer',
    'Intern',
    'summer',
    'intern',
    'Venture Architect',
    'venture architect',
    'Parttime',
    'parttime',
    'winter',
    'Winter',
    'General',
    'Assistant',
    'assistant',
    'Designer',
    'designer',
    'workshop',
    'Secretary',
    'secretary',
    'インターン',
    '秘書',
    'アシスタント',
    'Support',
    'support',
    'サポート',
    'engineer',
    'Engineer',
    'エンジニア',
    'Recruiter',
    'recruiter',
    'エンジニア'
]

accept_company = [
#     'Boston Consulting Group',
#     'Bain & Company',
#     'Kearney',
#     'Roland Berger',
#     'Strategy&',
#     'Arthur D. Little',
#     'Monitor Deloitte',
#     'Booz & Company',
#     'Dream Incubator',
#     'McKinsey',
#     'Oliver Wyman',
#     'Monitor Group',
#     'L.E.K. Consulting',
#     'Corporate Directions',
#     'Accenture',
#     'Goldman Sachs',
#     'Morgan Stanley',
#     'J.P. Morgan',
#     'Bank of America',
#     'Citi',
#     'U.S. Bank',
#     'Barclays',
#     'Deutsche Bank',
    'Credit Suisse',
#     'BNP Paribas',
#     'HSBC',
#     'Societe Generale',
#     'Société Générale'
]